# Generated by Django 5.0.7 on 2024-07-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_feedback_input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ManyToManyField(to='tag_feedback_input.post'),
        ),
    ]
