# Generated by Django 5.0.7 on 2024-07-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_feedback_input', '0002_remove_post_comment_id_comment_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='buyer_id',
        ),
    ]
