# Generated by Django 5.0.7 on 2024-07-31 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_feedback_input', '0003_remove_feedback_buyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyer_number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 8, 3)),
        ),
    ]
